import Head from "next/head";
import { api } from "~/utils/api";
import {
  Navbar,
  NavbarItem,
  NavbarBrand,
  Link,
  Button,
  Dropdown,
  DropdownTrigger,
  DropdownMenu,
  DropdownItem,
  Card,
  CardBody,
  CardFooter,
  Divider,
  Chip,
} from "@nextui-org/react";

import { SignInButton, SignUpButton } from "@clerk/nextjs";

export default function Home() {
  const { data: posts, isLoading } = api.posts.getAllPosts.useQuery();

  if (isLoading) return <div>loading...</div>;
  if (!posts) return <div>no posts</div>;

  return (
    <>
      <Head>
        <title>TECH INTERVIEWS</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Navbar>
          <NavbarBrand className="font-bold text-blue-400">
            TECH INTERVIEWS
          </NavbarBrand>
          <NavbarItem>
            <SignInButton>로그인</SignInButton>
          </NavbarItem>
          <NavbarItem>
            <SignUpButton>
              <Button color="primary">회원가입</Button>
            </SignUpButton>
          </NavbarItem>
        </Navbar>

        <Divider orientation="horizontal" />

        <main className="">
          <Dropdown>
            <DropdownTrigger>
              <Button variant="bordered">분류</Button>
            </DropdownTrigger>

            <DropdownMenu
              aria-labelledby="dropdown-trigger"
              onAction={(key) => console.log(key)}
            >
              <DropdownItem key="frontend">프론트엔드</DropdownItem>
            </DropdownMenu>
          </Dropdown>

          <Dropdown>
            <DropdownTrigger>
              <Button variant="bordered">정렬</Button>
            </DropdownTrigger>

            <DropdownMenu
              aria-labelledby="dropdown-trigger"
              onAction={(key) => console.log(key)}
            >
              <DropdownItem key="frontend">중요도순</DropdownItem>
              <DropdownItem key="frontend">빈도순</DropdownItem>
            </DropdownMenu>
          </Dropdown>

          <div>
            {posts.map((post) => {
              return (
                <Card className="cursor-pointer" key={post.id}>
                  <CardBody>
                    <h3>{post.title}</h3>
                  </CardBody>
                  <CardFooter>
                    <Chip variant="bordered">{post.category}</Chip>
                  </CardFooter>
                </Card>
              );
            })}
          </div>

          <div className="absolute bottom-3 right-3">
            <Link href="write">
              <Button>글쓰기</Button>
            </Link>
          </div>
        </main>

        <footer></footer>
      </div>
    </>
  );
}
