import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const { mutate } = api.posts.createPost.useMutation();
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <button
          onClick={() => {
            mutate({
              title: "My Post",
              content: "My Content",
            });
          }}
        >
          UPLOAD POST
        </button>
      </main>
    </>
  );
}
